# C?u h�nh Database
spring.datasource.url=jdbc:mysql://localhost:3306/bike_trading_v2?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=bnmbnmbnm123.
# T? ??ng t?o b?ng/c?p nh?t b?ng d?a tr�n Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# C?ng ch?y Backend
server.port=8081

# JWT Config (t�y ch?nh)
app.jwtSecret=BiketradingSecretKeyForJwtGenerationDoNotShareIt1234567890
app.jwtExpirationInMs=604800000

# --- VNPAY SANDBOX CONFIG ---
# (?�y l� m� test m?c ??nh c?a VNPay, �ng c� th? d�ng lu�n kh�ng c?n ??i)
vnpay.tmnCode=CGXZLS0Z
vnpay.hashSecret=XNBCJFAKAZQSGTARRLGCHVZWCIOIGSHN
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8081/api/vnpay/return