# App Name
spring.application.name=bike-trading-backend

# Server Port
server.port=8081

# MySQL Connection
# ??m b?o k?t th�c d�ng n�y b?ng d?u xu?ng d�ng, kh�ng ?? d�nh v?i d�ng d??i
spring.datasource.url=jdbc:mysql://localhost:3306/bike_trading_v2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=bnmbnmbnm123.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.address=0.0.0.0

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.profiles.active=dev

# JWT Configuration (??ng qu�n 2 d�ng n�y nh�)
app.jwtSecret=DayLaMotChuoiBaoMatRatDaiVaKhoDoanChoUngDungBikeTradingCuaBan123456!
app.jwtExpirationInMs=604800000